export function formatTradingViewWatchlist(symbols: readonly string[]): string {
  const unique = new Set<string>();
  for (const value of symbols) {
    const symbol = value.trim().toUpperCase().replace(/^NSE:/, '').replace(/-/g, '_');
    if (symbol) unique.add(`NSE:${symbol}`);
  }
  return [...unique].join(',');
}

export function renderSwingDashboard(basePath: string, authenticated: boolean, userName?: string): string {
  const api = `${basePath}/api/swing`;
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Swing Scanner • Trading Workspace</title>
<style>
*{box-sizing:border-box}body{margin:0;font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#f4f7fb;color:#172033}.shell{max-width:1440px;margin:auto;padding:24px}.topbar,.panel{background:#fff;border:1px solid #e1e8f0;border-radius:18px;box-shadow:0 6px 24px rgba(15,23,42,.06)}.topbar{padding:24px 28px;display:flex;align-items:center;justify-content:space-between;gap:20px;border-left:5px solid #7c3aed}.brand{display:flex;gap:14px;align-items:center}.brand-icon{width:48px;height:48px;border-radius:14px;background:linear-gradient(135deg,#7c3aed,#2563eb);display:grid;place-items:center;color:#fff;font-size:24px}.brand h1{font-size:24px;margin:0}.brand p{margin:4px 0 0;color:#64748b}.nav{display:flex;gap:8px;flex-wrap:wrap}.nav a,.button{border:0;border-radius:10px;padding:10px 14px;font-weight:700;text-decoration:none;cursor:pointer}.nav a{color:#475569;background:#f1f5f9}.nav a.active{color:#fff;background:#7c3aed}.button{background:#2563eb;color:#fff}.button:disabled{opacity:.55;cursor:not-allowed}.banner{margin:18px 0;padding:14px 18px;border-radius:12px;background:#fff7ed;border:1px solid #fed7aa;color:#9a3412}.banner.ok{background:#ecfdf5;border-color:#a7f3d0;color:#065f46}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin:18px 0}.metric{background:#fff;border:1px solid #e1e8f0;border-radius:14px;padding:18px}.metric span{display:block;color:#64748b;font-size:12px;text-transform:uppercase;letter-spacing:.07em}.metric strong{display:block;font-size:25px;margin-top:8px}.panel{padding:22px;margin-top:18px}.panel-head{display:flex;justify-content:space-between;align-items:center;gap:14px;margin-bottom:16px}.panel h2{font-size:18px;margin:0}.muted{color:#64748b}.blockers{display:flex;gap:8px;flex-wrap:wrap}.pill{display:inline-flex;padding:6px 9px;border-radius:999px;background:#fee2e2;color:#991b1b;font-size:12px;font-weight:700}.pill.good{background:#dcfce7;color:#166534}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:12px;border-bottom:1px solid #e8edf3;white-space:nowrap}th{font-size:12px;color:#64748b;text-transform:uppercase}.score{font-weight:800;color:#6d28d9}.empty{text-align:center;padding:44px;color:#64748b}.gate-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:10px}.gate{padding:13px;border:1px solid #e1e8f0;border-radius:12px}.gate strong{display:block}.gate small{color:#64748b}.error{color:#b91c1c}.footer{text-align:center;color:#94a3b8;padding:28px}@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}.topbar{align-items:flex-start;flex-direction:column}}@media(max-width:520px){.shell{padding:12px}.grid{grid-template-columns:1fr}}
</style>
<style>.custom-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px;margin-top:16px}.control{display:flex;flex-direction:column;gap:5px}.control label{font-size:11px;font-weight:800;color:#475569;text-transform:uppercase}.control input,.control select{border:1px solid #cbd5e1;border-radius:9px;padding:9px;background:#fff}.preset-row{display:flex;gap:10px;align-items:end;flex-wrap:wrap}.preset-row .control{min-width:260px}.check{flex-direction:row;align-items:center;padding-top:20px}.check input{width:auto}.pill.wait{background:#fef3c7;color:#92400e}.fail{max-width:380px;overflow:hidden;text-overflow:ellipsis;color:#b45309}details summary{cursor:pointer;font-size:18px;font-weight:800}.button.chart{background:#0f766e;text-decoration:none;display:inline-flex;align-items:center}.panel-actions{display:flex;gap:9px;flex-wrap:wrap}.notice{margin-top:10px;color:#64748b;font-size:13px}.research-highlight{border-left:5px solid #2563eb}.strict-empty{display:none}.quadrant{display:inline-flex;padding:5px 8px;border-radius:999px;font-size:11px;font-weight:800}.quadrant.LEADING{background:#dcfce7;color:#166534}.quadrant.IMPROVING{background:#dbeafe;color:#1d4ed8}.quadrant.WEAKENING{background:#ffedd5;color:#9a3412}.quadrant.LAGGING{background:#fee2e2;color:#991b1b}.quadrant.UNAVAILABLE{background:#e2e8f0;color:#475569}.scan-status{border-left:5px solid #64748b}.scan-status.running{border-left-color:#2563eb;background:linear-gradient(90deg,#eff6ff,#fff 32%)}.scan-status.complete{border-left-color:#16a34a}.scan-status.failed{border-left-color:#dc2626}.scan-title{display:flex;align-items:center;gap:10px}.spinner{display:none;width:18px;height:18px;border:3px solid #bfdbfe;border-top-color:#2563eb;border-radius:50%;animation:spin .8s linear infinite}.running .spinner{display:inline-block}@keyframes spin{to{transform:rotate(360deg)}}.progress-track{height:12px;background:#e2e8f0;border-radius:999px;overflow:hidden;margin:15px 0 10px}.progress-bar{height:100%;width:0;background:linear-gradient(90deg,#2563eb,#7c3aed);transition:width .35s ease}.scan-details{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:10px}.scan-detail{padding:10px 12px;border-radius:10px;background:#f8fafc}.scan-detail span{display:block;font-size:10px;text-transform:uppercase;color:#64748b}.scan-detail strong{display:block;margin-top:4px;font-size:14px}.scan-result{margin-top:12px;padding:11px 13px;border-radius:10px;background:#f1f5f9}.scan-result.changed{background:#ecfdf5;color:#166534}.scan-result.unchanged{background:#eff6ff;color:#1d4ed8}.scan-result.error{background:#fef2f2;color:#991b1b}</style>
</head>
<body><main class="shell">
<header class="topbar"><div class="brand"><div class="brand-icon">↗</div><div><h1>Swing Trading Scanner</h1><p>Nifty MidSmallcap 400 • Daily setups • Scanner only</p></div></div><nav class="nav"><a href="${basePath}/">Bollinger</a><a class="active" href="${basePath}/swing">Screener</a><a href="${basePath}/swing/watchlist/secondary">Secondary</a><a href="${basePath}/swing/watchlist/primary">Primary</a><a href="${basePath}/swing/sectors">Sectors</a></nav></header>
<div id="auth" class="banner ${authenticated ? 'ok' : ''}">${authenticated ? `Using the common Zerodha session${userName ? ` for ${escapeHtml(userName)}` : ''}. Trading and orders are disabled.` : `Authentication required. <a href="${basePath}/auth/login">Login with Zerodha</a>.`}</div>
<section class="grid"><div class="metric"><span>Service</span><strong id="service">${authenticated ? 'Loading' : 'AUTH REQUIRED'}</strong></div><div class="metric"><span>As of</span><strong id="asOf">—</strong></div><div class="metric"><span>Universe</span><strong id="universe">—</strong></div><div class="metric"><span>Strict qualified</span><strong id="qualified">—</strong></div><div class="metric"><span>Research candidates</span><strong id="researchCount">—</strong></div></section>
<section id="scanStatus" class="panel scan-status"><div class="panel-head"><div><div class="scan-title"><span class="spinner"></span><h2 id="scanPhase">Scanner ready</h2></div><div id="scanMessage" class="muted">Run a fresh screen or inspect industries rotating toward leadership.</div></div><div class="panel-actions"><a class="button chart" href="${basePath}/swing/sectors">Open Sector Rotation Chart →</a><button id="run" class="button" ${authenticated ? '' : 'disabled'}>Run scanner</button></div></div><div class="progress-track"><div id="scanProgress" class="progress-bar"></div></div><div class="scan-details"><div class="scan-detail"><span>Current activity</span><strong id="sync">Idle</strong></div><div class="scan-detail"><span>Data progress</span><strong id="dataProgress">—</strong></div><div class="scan-detail"><span>Data refreshed</span><strong id="dataChanged">—</strong></div><div class="scan-detail"><span>Elapsed</span><strong id="elapsed">—</strong></div><div class="scan-detail"><span>Latest data date</span><strong id="targetDate">—</strong></div><div class="scan-detail"><span>Last completed</span><strong id="lastCompleted">—</strong></div></div><div id="scanResult" class="scan-result">No scan started in this browser session.</div></section>
<details class="panel"><summary>Customize scan parameters</summary><div class="preset-row"><div class="control"><label>Screen preset</label><select id="preset"></select></div><button id="savePreset" class="button">Save custom</button><button id="reset" class="button">Reset</button></div><div class="custom-grid">
${scanInput('Minimum price ₹', 'minimumPrice', '1', '1')}${scanInput('Minimum traded value ₹', 'minimumAverageTradedValue', '100000', '1000000')}${scanInput('RS percentile ≥', 'relativeStrengthPercentile', '0', '1', '100')}${scanInput('RS slope sessions', 'relativeStrengthSlopeSessions', '2', '1', '60')}${scanInput('Minimum impulse %', 'minimumImpulseGain', '0', '1', '200', 100)}${scanInput('Accumulation days', 'minimumAccumulationDays', '1', '1', '20')}${scanInput('Volume dominance', 'minimumVolumeDominance', '0.1', '0.1', '10')}${scanInput('Maximum base depth %', 'maximumTighteningDepth', '1', '1', '50', 100)}${scanInput('FTA minimum sessions', 'minimumFinalTightAreaSessions', '2', '1', '20')}${scanInput('FTA maximum sessions', 'maximumFinalTightAreaSessions', '2', '1', '30')}${scanInput('FTA maximum depth %', 'maximumFinalTightAreaDepth', '1', '0.5', '30', 100)}${scanInput('Pivot distance from SMA10 %', 'maximumPivotDistanceFromSma10', '0', '0.5', '25', 100)}${scanInput('Upper-half closes', 'minimumUpperHalfCloses', '1', '1', '10')}${scanInput('Maximum ATR ratio', 'maximumAtrContraction', '0.1', '0.1', '2')}${scanInput('Maximum structural risk %', 'maximumStructuralRisk', '0.5', '0.5', '25', 100)}${scanInput('Sector percentile ≥', 'sectorPercentileThreshold', '0', '1', '100')}${scanInput('Qualified limit', 'topCandidates', '1', '1', '100')}${scanInput('Near-miss limit', 'nearMissLimit', '0', '1', '100')}
<div class="control"><label>Setup profile</label><select data-key="stageTwoMode"><option value="LOW_RISK">Low-risk momentum</option><option value="STRICT">Strict Minervini</option><option value="RESEARCH">Broad research</option></select></div><div class="control"><label>Market gate</label><select data-key="marketGateMode"><option value="REQUIRED">Required</option><option value="WATCHLIST">Show as WAIT_MARKET</option><option value="IGNORE">Ignore for research</option></select></div><div class="control check"><input data-key="requireVolumeContraction" type="checkbox"><label>Require volume contraction</label></div><div class="control check"><input data-key="requireRisingSma10" type="checkbox"><label>Require rising SMA10</label></div></div></details>
<section class="panel"><div class="panel-head"><div><h2>Safety status</h2><div id="safetySummary" class="muted">Loading scanner and corporate-action safeguards.</div></div></div><div id="blockers" class="blockers"><span class="pill">Loading…</span></div><div id="adjustmentPolicy" class="notice">Loading corporate-action adjustment QC…</div></section>
<section id="nearPanel" class="panel research-highlight"><div class="panel-head"><div><h2>Research candidates and near misses</h2><div class="muted">Unified ranking favors compact risk, tightness, demand evidence, relative strength, and sector context.</div></div><div class="panel-actions"><button id="downloadTradingView" class="button chart" type="button" disabled>Download TradingView list</button></div></div><div id="downloadNotice" class="notice">The download includes every qualified and research row currently displayed.</div><div class="table-wrap"><table><thead><tr><th>Rank</th><th>Symbol</th><th>Sector / industry</th><th>Sector quadrant</th><th>Add to watchlist</th><th>RS %ile</th><th>Low-risk score</th><th>Setup</th><th>Evidence</th><th>Company</th><th>Passed</th><th>Failed conditions</th></tr></thead><tbody id="nearMisses"><tr><td colspan="12" class="empty">Loading research candidates…</td></tr></tbody></table></div></section>
<section id="qualifiedPanel" class="panel"><div class="panel-head"><div><h2>Strictly qualified candidates</h2><div class="muted" id="scanMeta">Latest completed scan</div></div></div><div class="table-wrap"><table><thead><tr><th>Rank</th><th>Symbol</th><th>Sector / industry</th><th>Sector quadrant</th><th>Add to watchlist</th><th>RS %ile</th><th>Low-risk score</th><th>Setup</th><th>Evidence</th><th>Company</th><th>Score</th><th>Status</th><th>Risk</th></tr></thead><tbody id="candidates"><tr><td colspan="13" class="empty">Loading scanner results…</td></tr></tbody></table></div></section>
<section class="panel"><div class="panel-head"><h2>Gate diagnostics</h2></div><div id="gates" class="gate-grid"><div class="empty">Loading diagnostics…</div></div></section>
<div class="footer">Common authentication • Independent scanner state • No order capability</div>
</main>
<script>
const api=${JSON.stringify(api)},authenticated=${authenticated};let defaults=null,presets=[],watchlistStates={},observedScanId=null,observedScanTime=null,latestResult=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function json(path,options){const r=await fetch(api+path,options);const b=await r.json().catch(()=>({error:'Invalid response'}));if(!r.ok)throw new Error(b.error||b.details||('HTTP '+r.status));return b}
function tradingViewSymbols(result){const seen=new Set(),symbols=[];for(const candidate of [...(result?.topCandidates||[]),...(result?.nearMisses||[])]){const symbol=String(candidate?.symbol||'').trim().toUpperCase().replace(/^NSE:/,'').replace(/-/g,'_');const ticker=symbol?'NSE:'+symbol:'';if(ticker&&!seen.has(ticker)){seen.add(ticker);symbols.push(ticker)}}return symbols}
function updateTradingViewDownload(result){latestResult=result;const symbols=tradingViewSymbols(result),button=document.getElementById('downloadTradingView');button.disabled=symbols.length===0;button.textContent=symbols.length?'Download TradingView list ('+symbols.length+')':'Download TradingView list';document.getElementById('downloadNotice').textContent=symbols.length?'Exports all '+symbols.length+' unique displayed symbols as a TradingView-ready .txt file.':'No displayed candidates are available to export.'}
function downloadTradingView(){const symbols=tradingViewSymbols(latestResult);if(!symbols.length)return;const date=String(latestResult?.asOfDate||new Date().toISOString().slice(0,10)).replace(/[^0-9-]/g,''),blob=new Blob([symbols.join(',')],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='swing-scanner-'+date+'.txt';document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}
function setForm(p){document.querySelectorAll('[data-key]').forEach(el=>{const v=p[el.dataset.key];if(el.type==='checkbox')el.checked=Boolean(v);else el.value=typeof v==='number'&&el.dataset.scale?v*Number(el.dataset.scale):v})}
function collect(){const p={...defaults};document.querySelectorAll('[data-key]').forEach(el=>{const k=el.dataset.key;if(el.type==='checkbox')p[k]=el.checked;else if(el.tagName==='SELECT')p[k]=el.value;else p[k]=el.dataset.scale?Number(el.value)/Number(el.dataset.scale):Number(el.value)});return p}
function customPresets(){try{return JSON.parse(localStorage.getItem('swingCustomScreens')||'[]')}catch{return[]}}
function populatePresets(){const all=[...presets,...customPresets()];document.getElementById('preset').innerHTML=all.map(p=>'<option value="'+esc(p.id)+'">'+esc(p.name)+'</option>').join('');if(all[0])setForm(all[0].parameters)}
function quadrant(c){const q=c.sectorQuadrant||'UNAVAILABLE',title=q==='UNAVAILABLE'?'Sector rotation unavailable':('RS ratio '+Number(c.sectorRsRatio).toFixed(2)+' • Momentum '+Number(c.sectorMomentum).toFixed(2)+' • '+c.sectorRotationDate);return '<span class="quadrant '+q+'" title="'+esc(title)+'">'+esc(q)+'</span>'}
function setupLabels(c){const labels=c.setupLabels||[];return labels.length?labels.map(label=>'<span class="quadrant IMPROVING">'+esc(label.replaceAll('_',' '))+'</span>').join(' '):'<span class="muted">Developing</span>'}
function setupSignals(c){const e=c.setupEvidence;if(!e)return '—';const signals=(e.evidenceSignals||[]).slice(0,3).map(x=>x.replaceAll('_',' '));const title=(e.evidenceSignals||[]).join(' • ');return '<span title="'+esc(title)+'">'+esc(signals.join(' • ')||'No supporting signal')+'</span>'}
function render(result){document.getElementById('service').textContent=result.serviceStatus||'ONLINE';document.getElementById('asOf').textContent=result.asOfDate||'Never';document.getElementById('universe').textContent=result.universeCount??'—';const rows=result.topCandidates||[],near=result.nearMisses||[];document.getElementById('qualified').textContent=rows.length;document.getElementById('researchCount').textContent=near.length;document.getElementById('qualifiedPanel').classList.toggle('strict-empty',rows.length===0);const blocks=result.blocked||[];document.getElementById('blockers').innerHTML=blocks.length?blocks.map(x=>'<span class="pill">'+esc(x)+'</span>').join(''):'<span class="pill good">No blockers</span>';document.getElementById('scanMeta').textContent=result.generatedAt?'Generated '+new Date(result.generatedAt).toLocaleString():'No completed scan';document.getElementById('candidates').innerHTML=rows.length?rows.map((c,i)=>'<tr><td>#'+(i+1)+'</td><td><strong>'+esc(c.symbol)+'</strong></td><td>'+setupLabels(c)+'</td><td class="score">'+Number(c.lowRiskScore||0).toFixed(1)+'</td><td>'+setupSignals(c)+'</td><td>'+esc(c.company)+'</td><td>'+esc(c.sector)+'</td><td>'+quadrant(c)+'</td><td class="score">'+Number(c.score||0).toFixed(1)+'</td><td><span class="pill '+(c.status==='WAIT_MARKET'?'wait':'good')+'">'+esc(c.status)+'</span></td><td>'+(c.structuralRisk==null?'—':(c.structuralRisk*100).toFixed(2)+'%')+'</td><td>'+(c.rsPercentile==null?'—':Number(c.rsPercentile).toFixed(1))+'</td></tr>').join(''):'<tr><td colspan="13" class="empty">No stock passed the complete setup.</td></tr>';document.getElementById('nearMisses').innerHTML=near.length?near.map((c,i)=>'<tr><td>#'+(i+1)+'</td><td><strong>'+esc(c.symbol)+'</strong></td><td>'+setupLabels(c)+'</td><td class="score">'+Number(c.lowRiskScore||0).toFixed(1)+'</td><td>'+setupSignals(c)+'</td><td>'+esc(c.company)+'</td><td>'+esc(c.sector||'UNMAPPED')+'</td><td>'+quadrant(c)+'</td><td>'+Number(c.rsPercentile||0).toFixed(1)+'</td><td>'+esc(c.passedGateCount)+' / '+esc(c.evaluatedGateCount)+'</td><td class="fail" title="'+esc((c.failedGateCodes||[]).join(', '))+'">'+esc((c.failedGateCodes||[]).join(', '))+'</td></tr>').join(''):'<tr><td colspan="12" class="empty">No eligible near misses for this run.</td></tr>'}
function shortlist(c){const state=watchlistStates[c.symbol];if(state)return '<span class="pill good">IN '+state+'</span>';return '<button class="button" data-add-secondary="'+esc(c.symbol)+'">Add to Secondary</button>'}
async function addSecondary(symbol){try{await json('/watchlists/secondary/add',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({symbols:[symbol]})});watchlistStates[symbol]='SECONDARY';await load()}catch(e){alert(e.message)}}
function applyShortlistButtons(id,items){document.querySelectorAll('#'+id+' [data-add-secondary]').forEach(button=>button.addEventListener('click',()=>addSecondary(button.dataset.addSecondary)))}
function render(result){document.getElementById('service').textContent=result.serviceStatus||'ONLINE';document.getElementById('asOf').textContent=result.asOfDate||'Never';document.getElementById('universe').textContent=result.universeCount??'—';const rows=result.topCandidates||[],near=result.nearMisses||[];document.getElementById('qualified').textContent=rows.length;document.getElementById('researchCount').textContent=near.length;document.getElementById('qualifiedPanel').classList.toggle('strict-empty',rows.length===0);const blocks=result.blocked||[];document.getElementById('blockers').innerHTML=blocks.length?blocks.map(x=>'<span class="pill">'+esc(x)+'</span>').join(''):'<span class="pill good">No blockers</span>';document.getElementById('scanMeta').textContent=result.generatedAt?'Generated '+new Date(result.generatedAt).toLocaleString():'No completed scan';document.getElementById('candidates').innerHTML=rows.length?rows.map((c,i)=>'<tr><td>#'+(i+1)+'</td><td><strong>'+esc(c.symbol)+'</strong></td><td>'+esc(c.company)+'</td><td>'+esc(c.sector)+'</td><td>'+quadrant(c)+'</td><td class="score">'+Number(c.score||0).toFixed(1)+'</td><td><span class="pill '+(c.status==='WAIT_MARKET'?'wait':'good')+'">'+esc(c.status)+'</span></td><td>'+(c.structuralRisk==null?'—':(c.structuralRisk*100).toFixed(2)+'%')+'</td><td>'+(c.rsPercentile==null?'—':Number(c.rsPercentile).toFixed(1))+'</td></tr>').join(''):'<tr><td colspan="9" class="empty">No stock passed the complete setup.</td></tr>';document.getElementById('nearMisses').innerHTML=near.length?near.map((c,i)=>'<tr><td>#'+(i+1)+'</td><td><strong>'+esc(c.symbol)+'</strong></td><td>'+esc(c.company)+'</td><td>'+esc(c.sector||'UNMAPPED')+'</td><td>'+quadrant(c)+'</td><td>'+Number(c.rsPercentile||0).toFixed(1)+'</td><td>'+esc(c.passedGateCount)+' / '+esc(c.evaluatedGateCount)+'</td><td class="fail" title="'+esc((c.failedGateCodes||[]).join(', '))+'">'+esc((c.failedGateCodes||[]).join(', '))+'</td></tr>').join(''):'<tr><td colspan="8" class="empty">No eligible near misses for this screen.</td></tr>'}
function renderSetupEvidence(result){render(result);updateTradingViewDownload(result);const rows=result.topCandidates||[],near=result.nearMisses||[];document.getElementById('candidates').innerHTML=rows.length?rows.map((c,i)=>'<tr><td>#'+(i+1)+'</td><td><strong>'+esc(c.symbol)+'</strong></td><td>'+esc(c.sector||'UNMAPPED')+'</td><td>'+quadrant(c)+'</td><td>'+shortlist(c)+'</td><td>'+(c.rsPercentile==null?'—':Number(c.rsPercentile).toFixed(1))+'</td><td class="score">'+Number(c.lowRiskScore||0).toFixed(1)+'</td><td>'+setupLabels(c)+'</td><td>'+setupSignals(c)+'</td><td>'+esc(c.company)+'</td><td class="score">'+Number(c.score||0).toFixed(1)+'</td><td><span class="pill '+(c.status==='WAIT_MARKET'?'wait':'good')+'">'+esc(c.status)+'</span></td><td>'+(c.structuralRisk==null?'—':(c.structuralRisk*100).toFixed(2)+'%')+'</td></tr>').join(''):'<tr><td colspan="13" class="empty">No stock passed the complete setup.</td></tr>';document.getElementById('nearMisses').innerHTML=near.length?near.map((c,i)=>'<tr><td>#'+(i+1)+'</td><td><strong>'+esc(c.symbol)+'</strong></td><td>'+esc(c.sector||'UNMAPPED')+'</td><td>'+quadrant(c)+'</td><td>'+shortlist(c)+'</td><td>'+(c.rsPercentile==null?'—':Number(c.rsPercentile).toFixed(1))+'</td><td class="score">'+Number(c.lowRiskScore||0).toFixed(1)+'</td><td>'+setupLabels(c)+'</td><td>'+setupSignals(c)+'</td><td>'+esc(c.company)+'</td><td>'+esc(c.passedGateCount)+' / '+esc(c.evaluatedGateCount)+'</td><td class="fail" title="'+esc((c.failedGateCodes||[]).join(', '))+'">'+esc((c.failedGateCodes||[]).join(', '))+'</td></tr>').join(''):'<tr><td colspan="12" class="empty">No eligible near misses for this run.</td></tr>'}
function renderSync(s){if(!s)return 0;const progress=s.totalSymbols?Math.round((s.completedSymbols||0)*100/s.totalSymbols):0;const phase=String(s.phase||'IDLE').replaceAll('_',' ').toLowerCase();document.getElementById('sync').textContent=s.running?(phase+(s.currentSymbol?' • '+s.currentSymbol:'')):phase;document.getElementById('dataProgress').textContent=s.totalSymbols?((s.completedSymbols||0)+' / '+s.totalSymbols+' symbols ('+progress+'%)'):'Waiting';document.getElementById('dataChanged').textContent=(s.updatedSymbols||0)+' symbols • '+(s.candlesImported||0)+' candles'+(s.failedSymbols?' • '+s.failedSymbols+' failed':'');document.getElementById('targetDate').textContent=s.targetDate||'—';return progress}
function elapsed(start,end){if(!start)return '—';const seconds=Math.max(0,Math.round((new Date(end||Date.now())-new Date(start))/1000));return seconds<60?seconds+'s':Math.floor(seconds/60)+'m '+seconds%60+'s'}
function renderScanStatus(service){const scan=service.scan||{},sync=service.dataSync||{},running=Boolean(service.running||scan.running),panel=document.getElementById('scanStatus'),button=document.getElementById('run');panel.classList.toggle('running',running);panel.classList.toggle('complete',scan.phase==='COMPLETE');panel.classList.toggle('failed',scan.phase==='FAILED');button.disabled=!authenticated||running;button.textContent=running?'Scanner running…':'Run scanner';const labels={IDLE:'Scanner ready',UNIVERSE:'Refreshing stock universe',DATA_SYNC:'Refreshing market data',SCREENING:'Evaluating stock setups',SECTOR_ROTATION:'Calculating sector rotation',SAVING:'Saving new results',COMPLETE:'Scan completed',FAILED:'Scan failed'};document.getElementById('scanPhase').textContent=labels[scan.phase]||'Scanner ready';document.getElementById('scanMessage').textContent=scan.message||'Ready to run';document.getElementById('elapsed').textContent=elapsed(scan.startedAt,scan.completedAt);document.getElementById('lastCompleted').textContent=scan.completedAt?new Date(scan.completedAt).toLocaleString():(service.latestScanTime?new Date(service.latestScanTime).toLocaleString():'—');const syncProgress=renderSync(sync),phaseProgress={IDLE:0,UNIVERSE:5,DATA_SYNC:10,SCREENING:82,SECTOR_ROTATION:90,SAVING:96,COMPLETE:100,FAILED:100};document.getElementById('scanProgress').style.width=(scan.phase==='DATA_SYNC'?10+Math.round(syncProgress*.7):(phaseProgress[scan.phase]||0))+'%';const box=document.getElementById('scanResult');box.className='scan-result';if(scan.phase==='FAILED'){box.classList.add('error');box.textContent=scan.lastError||'Scanner failed'}else if(scan.phase==='COMPLETE'){box.classList.add(scan.resultsChanged?'changed':'unchanged');const change=scan.resultsChanged?('New list loaded • '+scan.addedSymbols.length+' added • '+scan.removedSymbols.length+' removed'):'No changes from the previous research list';box.textContent=change+' • '+scan.researchCount+' research • '+scan.qualifiedCount+' qualified • Scan '+scan.scanId}else if(running){box.textContent='Please keep this page open. Results will refresh automatically when screening completes.'}else if(service.latestScanId){box.textContent='Latest saved scan '+service.latestScanId+' • Data through '+(service.dataQuality?.latestDate||'—')}}
function renderAdjustmentPolicy(response,blocks){const policy=response?.policy,verified=policy?.status==='VERIFIED';document.getElementById('safetySummary').textContent=blocks.length?'Safety blockers require attention; research candidates remain available.':'All configured scanner data safeguards passed. Trading remains disabled.';const node=document.getElementById('adjustmentPolicy');if(!policy){node.textContent='Corporate-action policy has not been validated.';return}node.innerHTML=verified?'<strong>Corporate-action QC verified</strong> • '+policy.symbolsChecked+' symbols • '+policy.structuralActions+' splits/bonuses • '+policy.dividendsChecked+' dividends • '+policy.canonicalMatches+'/'+policy.actionsChecked+' Kite comparisons passed • '+policy.symbolsReconciled+' histories reconciled • Checked '+new Date(policy.checkedAt).toLocaleString():'<strong>Corporate-action QC '+esc(policy.status)+'</strong> • '+policy.failures+' failures across '+policy.actionsChecked+' actions'}
async function refreshRunStatus(){try{const service=await json('/status');renderScanStatus(service);if(observedScanTime&&service.latestScanTime!==observedScanTime&&!service.running){observedScanId=service.latestScanId;observedScanTime=service.latestScanTime;await load()}else if(!observedScanTime){observedScanId=service.latestScanId;observedScanTime=service.latestScanTime}}catch(e){document.getElementById('scanMessage').textContent=e.message}}
async function load(){try{const [status,gates,service,config,watchlists,adjustmentQc]=await Promise.all([json('/results/latest'),json('/gates'),json('/status'),json('/config'),json('/watchlists/status'),json('/corporate-actions/qc')]);observedScanId=service.latestScanId;observedScanTime=service.latestScanTime;watchlistStates=watchlists.states||{};if(!defaults){defaults=config.defaults;presets=config.presets;populatePresets()}renderSetupEvidence(status);renderAdjustmentPolicy(adjustmentQc,status.blocked||[]);applyShortlistButtons('candidates',status.topCandidates||[]);applyShortlistButtons('nearMisses',status.nearMisses||[]);renderScanStatus(service);document.getElementById('gates').innerHTML=(gates.gates||[]).map(g=>'<div class="gate"><strong>'+esc(g.gate)+'</strong><small>'+g.passed+' passed • '+g.failed+' failed</small></div>').join('')||'<div class="empty">No gate evidence yet.</div>'}catch(e){document.getElementById('service').textContent='OFFLINE';document.getElementById('blockers').innerHTML='<span class="pill">'+esc(e.message)+'</span>'}}
document.getElementById('preset').addEventListener('change',e=>{const p=[...presets,...customPresets()].find(x=>x.id===e.target.value);if(p)setForm(p.parameters)});document.getElementById('reset').addEventListener('click',()=>setForm(defaults));document.getElementById('savePreset').addEventListener('click',()=>{const name=prompt('Name this custom screen');if(!name)return;const list=customPresets(),p={id:'custom-'+Date.now(),name,parameters:collect()};list.push(p);localStorage.setItem('swingCustomScreens',JSON.stringify(list));populatePresets();document.getElementById('preset').value=p.id});
document.getElementById('downloadTradingView').addEventListener('click',downloadTradingView);
document.getElementById('run').addEventListener('click',async e=>{const b=e.currentTarget;if(b.disabled)return;b.disabled=true;document.getElementById('scanResult').textContent='Starting scanner…';try{await json('/scan',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({parameters:collect()})});await load()}catch(err){await refreshRunStatus();document.getElementById('scanResult').className='scan-result error';document.getElementById('scanResult').textContent=err.message}});if(authenticated){load();setInterval(refreshRunStatus,1000);setInterval(load,60000)}else{document.getElementById('blockers').innerHTML='<span class="pill">COMMON_AUTH_REQUIRED</span>';document.getElementById('candidates').innerHTML='<tr><td colspan="8" class="empty">Login once through the Bollinger dashboard to view scanner results.</td></tr>';document.getElementById('gates').innerHTML='<div class="empty">Gate evidence is available after authentication.</div>'}
</script></body></html>`;
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (character) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  })[character] || character);
}

function scanInput(label: string, key: string, min: string, step: string, max = '', scale?: number): string {
  return `<div class="control"><label>${label}</label><input data-key="${key}"${scale ? ` data-scale="${scale}"` : ''} type="number" min="${min}"${max ? ` max="${max}"` : ''} step="${step}"></div>`;
}
