export function renderWatchlistDashboard(
  basePath: string, authenticated: boolean, state: 'SECONDARY' | 'PRIMARY', userName?: string,
): string {
  const secondary = state === 'SECONDARY';
  const title = secondary ? 'Secondary Watchlist' : 'Primary Watchlist';
  const description = secondary
    ? 'Research shortlist grouped by sector. Remove noise, then promote the strongest names.'
    : 'Manually curated actionable-review names. This is not order authorization.';
  const accent = secondary ? '#2563eb' : '#16a34a';

  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} • Swing Workspace</title><style>
*{box-sizing:border-box}body{margin:0;font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#f4f7fb;color:#172033}.shell{max-width:1440px;margin:auto;padding:24px}.topbar,.sector{background:#fff;border:1px solid #e1e8f0;border-radius:18px;box-shadow:0 6px 24px rgba(15,23,42,.06)}.topbar{padding:22px 28px;display:flex;justify-content:space-between;align-items:center;gap:18px;border-left:5px solid ${accent}}.brand h1{margin:0;font-size:24px}.brand p{margin:5px 0 0;color:#64748b}.nav{display:flex;gap:8px;flex-wrap:wrap}.nav a,.button{border:0;border-radius:9px;padding:9px 12px;text-decoration:none;font-weight:700;cursor:pointer}.nav a{background:#f1f5f9;color:#475569}.nav a.active{background:${accent};color:#fff}.banner{margin:18px 0;padding:13px 17px;border-radius:12px;background:#ecfdf5;border:1px solid #a7f3d0;color:#065f46}.banner.warn{background:#fff7ed;border-color:#fed7aa;color:#9a3412}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:18px 0}.metric{background:#fff;border:1px solid #e1e8f0;border-radius:14px;padding:18px}.metric span{font-size:11px;color:#64748b;text-transform:uppercase}.metric strong{display:block;font-size:24px;margin-top:8px}.sector{margin-top:16px;overflow:hidden}.sector-head{padding:17px 20px;display:flex;justify-content:space-between;align-items:center;background:#f8fafc}.sector-head h2{margin:0;font-size:17px}.badge{padding:5px 8px;border-radius:999px;font-size:11px;font-weight:800}.LEADING{background:#dcfce7;color:#166534}.IMPROVING{background:#dbeafe;color:#1d4ed8}.WEAKENING{background:#ffedd5;color:#9a3412}.LAGGING{background:#fee2e2;color:#991b1b}.UNAVAILABLE{background:#e2e8f0;color:#475569}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:11px;border-top:1px solid #e8edf3;white-space:nowrap}th{font-size:11px;text-transform:uppercase;color:#64748b}.button{background:#e2e8f0;color:#334155}.promote{background:#dcfce7;color:#166534}.demote{background:#dbeafe;color:#1d4ed8}.archive{background:#fee2e2;color:#991b1b}.priority,.notes{border:1px solid #cbd5e1;border-radius:8px;padding:8px}.notes{min-width:240px}.empty{background:#fff;border:1px dashed #cbd5e1;border-radius:14px;padding:30px;text-align:center;color:#64748b}.footer{margin:20px;text-align:center;color:#64748b;font-size:12px}@media(max-width:850px){.topbar{align-items:flex-start;flex-direction:column}.metrics{grid-template-columns:repeat(2,1fr)}}
</style></head><body><main class="shell"><header class="topbar"><div class="brand"><h1>${title}</h1><p>${description}</p></div><nav class="nav"><a href="${basePath}/swing">Screener</a><a class="${secondary ? 'active' : ''}" href="${basePath}/swing/watchlist/secondary">Secondary</a><a class="${secondary ? '' : 'active'}" href="${basePath}/swing/watchlist/primary">Primary</a><a href="${basePath}/swing/sectors">Sector Rotation</a></nav></header><div class="banner ${authenticated ? '' : 'warn'}">${authenticated ? `Common session active${userName ? ` for ${escapeHtml(userName)}` : ''}. Scanner-only workflow; no order capability.` : `Authentication required. <a href="${basePath}/auth/login">Login with Zerodha</a>.`}</div><section class="metrics"><div class="metric"><span>Total names</span><strong id="total">—</strong></div><div class="metric"><span>Leading sectors</span><strong id="leading">—</strong></div><div class="metric"><span>Improving sectors</span><strong id="improving">—</strong></div><div class="metric"><span>Top priority</span><strong id="priority">—</strong></div></section><div id="content"><div class="empty">Loading ${title.toLowerCase()}…</div></div><div class="footer">Manual curation only • Corporate-action safety blocker remains • Trading disabled</div></main><script>
const api=${JSON.stringify(`${basePath}/api/swing`)},state=${JSON.stringify(state)};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function request(path,options){const r=await fetch(api+path,options),b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'Request failed');return b}
function quadrant(c){return c.sectorQuadrant||'UNAVAILABLE'}
function row(entry){const c=entry.candidate,next=state==='SECONDARY'?'PRIMARY':'SECONDARY',label=state==='SECONDARY'?'Promote':'Demote',kind=state==='SECONDARY'?'promote':'demote';return '<tr><td><strong>'+esc(entry.symbol)+'</strong><br><small>'+esc(entry.company)+'</small></td><td><span class="badge '+quadrant(c)+'">'+quadrant(c)+'</span></td><td>'+Number(c.rsPercentile||0).toFixed(1)+'</td><td>'+esc(c.passedGateCount||0)+' / '+esc(c.evaluatedGateCount||0)+'</td><td>'+(c.structuralRisk==null?'—':(c.structuralRisk*100).toFixed(2)+'%')+'</td><td><select class="priority" data-priority="'+esc(entry.symbol)+'">'+[0,1,2,3,4,5].map(x=>'<option '+(x===entry.priority?'selected':'')+' value="'+x+'">P'+x+'</option>').join('')+'</select></td><td><input class="notes" data-notes="'+esc(entry.symbol)+'" maxlength="2000" value="'+esc(entry.notes)+'" placeholder="Review notes"></td><td><button class="button" data-save="'+esc(entry.symbol)+'">Save</button> <button class="button '+kind+'" data-move="'+esc(entry.symbol)+'" data-next="'+next+'">'+label+'</button> <button class="button archive" data-move="'+esc(entry.symbol)+'" data-next="ARCHIVED">Remove</button></td></tr>'}
function bind(){document.querySelectorAll('[data-save]').forEach(b=>b.addEventListener('click',()=>save(b.dataset.save)));document.querySelectorAll('[data-move]').forEach(b=>b.addEventListener('click',()=>move(b.dataset.move,b.dataset.next)))}
function render(entries){document.getElementById('total').textContent=entries.length;const sectors=new Map;entries.forEach(e=>sectors.set(e.sector,[...(sectors.get(e.sector)||[]),e]));const order={LEADING:0,IMPROVING:1,WEAKENING:2,LAGGING:3,UNAVAILABLE:4};const groups=[...sectors.entries()].sort((a,b)=>order[quadrant(a[1][0].candidate)]-order[quadrant(b[1][0].candidate)]||(b[1][0].candidate.sectorRsRatio||0)-(a[1][0].candidate.sectorRsRatio||0));document.getElementById('leading').textContent=groups.filter(g=>quadrant(g[1][0].candidate)==='LEADING').length;document.getElementById('improving').textContent=groups.filter(g=>quadrant(g[1][0].candidate)==='IMPROVING').length;document.getElementById('priority').textContent=entries.filter(e=>e.priority>=4).length;document.getElementById('content').innerHTML=groups.length?groups.map(([sector,items])=>{const c=items[0].candidate;return '<section class="sector"><div class="sector-head"><h2>'+esc(sector)+' <span class="badge '+quadrant(c)+'">'+quadrant(c)+'</span></h2><span>RS ratio '+Number(c.sectorRsRatio||0).toFixed(2)+' • Momentum '+Number(c.sectorMomentum||0).toFixed(2)+'</span></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Quadrant</th><th>Stock RS</th><th>Gates</th><th>Risk</th><th>Priority</th><th>Notes</th><th>Actions</th></tr></thead><tbody>'+items.map(row).join('')+'</tbody></table></div></section>'}).join(''):'<div class="empty">No names in this watchlist. Add candidates from the Screener.</div>';bind()}
async function load(){try{render((await request('/watchlists/'+state)).entries)}catch(e){document.getElementById('content').innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}
async function move(symbol,next){if(next==='ARCHIVED'&&!confirm('Remove '+symbol+' from this watchlist?'))return;try{await request('/watchlists/'+encodeURIComponent(symbol)+'/state',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({state:next})});await load()}catch(e){alert(e.message)}}
async function save(symbol){try{await request('/watchlists/'+encodeURIComponent(symbol)+'/details',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({notes:document.querySelector('[data-notes="'+symbol+'"]').value,priority:Number(document.querySelector('[data-priority="'+symbol+'"]').value)})});await load()}catch(e){alert(e.message)}}
${authenticated ? 'load()' : ''}
</script></body></html>`;
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character] || character);
}
